### ISSUE TITLE
Relative Paths not working on MJML with mjml-react

### ISSUE THREAD

**Issue by alioshr** [wix-incubator/mjml-react-example#3] opened 2020-12-14 16:30 UTC
I have a template being shipped with ```nodemailer``` and all works just fine, except for the fact that I am getting broken images on the email, once received on the inbox.

Relative paths do not work at all. I have also tried some links from images in the web, google drive, google images, and they also not work.

The only links that work are links that end with the file name/type (e.g ......jpg) , like the src below: 

```
 <MjmlImage
              width="400px"
              src="https://image.shutterstock.com/image-photo/bright-spring-view-cameo-island-260nw-1048185397.jpg"
            ></MjmlImage>
```

I tried using [mjml-with-images-loader](https://developer.aliyun.com/mirror/npm/package/mjml-with-images-loader) and configured the module exports on my NextJs  config file, but nothing worked. I guess that it did not work due to the fact that I am using ```mjml-react``` on top of the raw ```mjml syntax```.

Thanks in advance for any help on this as I do not know what is the best solution regarding the image path links, if I can get the local relative paths to be transformed into html string or if I should get these images on the web and then referentiate them on my ```src```

**Comment by mastertheblaster** [comment] 2020-12-14 20:51
Hey @alioshr 

This one is a duplicate of https://github.com/wix-incubator/mjml-react/issues/48 So I am closing this one and keeping the conversation in one place.

Cheers

**Closed as completed by mastertheblaster** 2020-12-14 20:51 UTC
